### PR TITLE
SONARGITUB-24 Add image title for severity

### PR DESCRIPTION
**Pull request by janos-ss**

### CODE REVIEW

**Comment by janos-ss** [comment]
@henryju I guess the main question is what is a good format for the image title

**Comment by ofirnk** [comment]
A bit late to the party - but single qoutes would've worked also :) and make the string more readable:
INFO = `INFO`

**Comment by janos-ss** [comment]
@ofirnk better late than never ;-) You mean, the Java code is more readable that way, because I don't have to escape embedded double-quotes, is that it? Sounds like a good idea, thanks!

**Comment by ofirnk** [comment]
@janos-ss exactly :+1:

**Pull request merged**
