### PR TITLE
Add a parameter to control how many issues to display in the summary

### PR DESCRIPTION
**Pull request by gjacquet**
Add a parameter to control how many issues to display in the summary: (sonar.github.maxGlobalIssues).

You can find the long story there: #9

### CODE REVIEW

**Comment by henryju** [comment]
The point is that GitHub comments can't contain too many characters (see https://jira.sonarsource.com/browse/SONARGITUB-15). Our position is:
* if your P/R contains more than 10 issues, then start by fixing these 10, then update you're branch and you'll "see" the next 10 issues. GitHub plugin is supposed to be a safety net anyway. Developers should use SonarLint to catch most issues.
* if you really want a "report", then this is not the goal of the GitHub plugin. Please use SonarLint for CLI (or the issues report feature) to generate a HTML report.

Does it make sense?

**Comment by gjacquet** [comment]
We can't really use sonarlint until we can plug it into our sonar instance with our rules.

Maybe we don't need to display more issues but we could change the message to make it more obvious what the intent of this summary is.

As is, people felt like it was showing the first lines of a report and the whole thing could be accessed somewhere else... So maybe instead of:

>SonarQube analysis reported 25 issues:
>* BLOCKER 3 blocker
> * MAJOR 16 major
> * MINOR 5 minor
> * INFO 1 info
>
>Watch the comments in this conversation to review them.
>Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
>* MAJOR [Reduce the total number of break and continue statements in this loop to use at most one.](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/integration/custom/azure/service/MicrosoftMembershipSyncServiceImpl.java#L146) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS135)
> * MAJOR [Line!](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/integration/custom/azure/service/MicrosoftMembershipSyncServiceImpl.java#L199) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=checkstyle%3ADouble_empty_line)
>* MAJOR [Please use a single space](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/integration/custom/azure/service/MicrosoftMembershipSyncServiceImpl.java#L364) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=checkstyle%3ANo_double_space)
>* MAJOR [Add a private constructor to hide the implicit public one.](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/integration/custom/mosi/service/MicrosoftConstants.java#L7) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS1118)
> * MAJOR [The Cyclomatic Complexity of this method "initRoles" is 14 which is greater than 10 authorized.](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L156) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
>* MAJOR [Introduce a new variable instead of reusing the parameter "role".](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L162) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS1226)
>* MINOR [Remove this use of "PasswordEncoder"; it is deprecated.](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L49) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)
>* BLOCKER [NullPointerException might be thrown as 'invitation' is nullable here](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L63) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS2259)
>* BLOCKER [NullPointerException might be thrown as 'invitation' is nullable here](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L96) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS2259)
>* BLOCKER [NullPointerException might be thrown as 'invitation' is nullable here](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L115) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS2259)
>* ... 13 more

We could have something like:

> #### Analysis summary
>SonarQube analysis reported 25 issues:
>* BLOCKER 3 blocker
> * MAJOR 16 major
> * MINOR 5 minor
> * INFO 1 info
>
>Watch the comments in this conversation to review them.
> #### Top 10 unreported issues
>Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:
>1. BLOCKER [NullPointerException might be thrown as 'invitation' is nullable here](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L63) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS2259)
>2. BLOCKER [NullPointerException might be thrown as 'invitation' is nullable here](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L96) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS2259)
>3. BLOCKER [NullPointerException might be thrown as 'invitation' is nullable here](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L115) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS2259)
>4. MAJOR [Reduce the total number of break and continue statements in this loop to use at most one.](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/integration/custom/azure/service/MicrosoftMembershipSyncServiceImpl.java#L146) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS135)
>5. MAJOR [Line!](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/integration/custom/azure/service/MicrosoftMembershipSyncServiceImpl.java#L199) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=checkstyle%3ADouble_empty_line)
>6. MAJOR [Please use a single space](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/integration/custom/azure/service/MicrosoftMembershipSyncServiceImpl.java#L364) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=checkstyle%3ANo_double_space)
>7. MAJOR [Add a private constructor to hide the implicit public one.](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/integration/custom/mosi/service/MicrosoftConstants.java#L7) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS1118)
> 8. MAJOR [The Cyclomatic Complexity of this method "initRoles" is 14 which is greater than 10 authorized.](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L156) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AMethodCyclomaticComplexity)
>9. MAJOR [Introduce a new variable instead of reusing the parameter "role".](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L162) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3AS1226)
>10. MINOR [Remove this use of "PasswordEncoder"; it is deprecated.](https://github.com/AppDirect/AppDirect/blob/58ae09b42f1b1079639c87c12a879befd8bc3fc2/appdirect-parent/appdirect/src/main/java/com/appdirect/backend/user/service/InvitationHelper.java#L49) [rule](https://sonar.appdirectondemand.com/coding_rules#rule_key=squid%3ACallToDeprecatedMethod)

Could avoid some questions :smile:

**Comment by henryju** [comment]
@bellingard WDYT of the proposal ("Top 10 " instead of '...XXX more')? Personally I like the idea.

**Comment by bellingard** [comment]
@henryju If I understand correctly, this PR allows to sort the first X "unreported" issues by severity, right? (X being customisable) If yes, then I'm +1, this is a valuable contribution. Thanks @gjacquet

**Comment by henryju** [comment]
@bellingard Nope, this is the other P/R #9 This one was initially about providing a parameter to allow increasing number of reported issues (currently  hardcoded to 10). But I manage to convince @gjacquet  this is not a good idea so he is now proposing to update wording to make it more clear we are only reporting the first 10 issues, and that user should not expect to have a way to "see" the following ones (except by fixing the first 10 and updating the P/R of course). The previous screenshot is a mock of what would be the final result with #9 + #10

**Comment by bellingard** [comment]
@henryju OK, so this is even better.

**Comment by gjacquet** [comment]
Updated display a bit... What do you think?
I am trying to make it more clear what each clickable elements link to. I also wanted to make it easier to see where the issues are.

I added the filename and the line to the issue list. Filename links to the file and issue message links to the rule.

#### Analysis summary
SonarQube analysis reported 9 issues:
* MAJOR 3 major
* MINOR 2 minor
* INFO 4 info

Watch the comments in this conversation to review them.

#### Top 3 unreported issues

Note: the following issues could not be reported as comments because they are located on lines that are not displayed in this pull request:

1. MAJOR [OAuthConfiguration.java#L32](http://www.appdirect.com): [Please remove trailing whitespace](http://www.appdirect.com/coding_rules#rule_key=checkstyle%3ANo_trailing_whitespace)
1. MAJOR [OAuthConfiguration.java#L37](http://www.appdirect.com): [Please remove trailing whitespace](http://www.appdirect.com/coding_rules#rule_key=checkstyle%3ANo_trailing_whitespace)
1. MAJOR [OAuthConfiguration.java#L60](http://www.appdirect.com): [Please remove trailing whitespace](http://www.appdirect.com/coding_rules#rule_key=checkstyle%3ANo_trailing_whitespace)

**Comment by henryju** [comment]
Looks good to put the name + line of the file but I would not separate the severity icon from the rule message. Also keeping the rule description in a separate button is consistant with what is reported for inline comments. So either we also change inline comments, or we keep the previous icon. Something like:

1. [OAuthConfiguration.java#L32](http://www.appdirect.com): MAJOR Please remove trailing whitespace [rule](http://www.appdirect.com/coding_rules#rule_key=squid%3AS1118)
1. [OAuthConfiguration.java#L37](http://www.appdirect.com): MAJOR Please remove trailing whitespace [rule](http://www.appdirect.com/coding_rules#rule_key=squid%3AS1118)
1. [OAuthConfiguration.java#L60](http://www.appdirect.com): MAJOR Please remove trailing whitespace [rule](http://www.appdirect.com/coding_rules#rule_key=squid%3AS1118)

**Comment by gjacquet** [comment]
Looks like this now:
image

**Comment by gjacquet** [comment]
@henryju I'll be on vacation for the next three weeks.
If you have other comments, I'll address them when I return.

**Comment by henryju** [comment]
@gjacquet Thanks for the notification and enjoy your holidays ;)

**Pull request merged**
