### PR TITLE
Property to disable deleting old comments from pull requests

### PR DESCRIPTION
**Pull request by piotrwach**
I want to be able to leave old comments for issues that have been resolved on pull requests.

### CODE REVIEW

**Comment by ofirnk** [comment]
:smile: 
https://github.com/SonarSource/sonar-github/pull/22

@henryju If I'm allowed to retract my previous comment on my PR - after going with our fork for several months now - it's better for us to leave the old comments under no condition: whether they were commented or not.

So, :+1:  for this PR

**Comment by henryju** [comment]
Sorry but I fail to see the value of keeping outdated comments. How would you distinguish the remaining issues from the one that were already fixed?

**Comment by ofirnk** [comment]
@henryju  After the commiter updates her code Github automatically marks the comments as outdated. As the "summary comment" is still updated - you get an up to ~date~ head view of the remaining issues in the PR

**Comment by henryju** [comment]
@ofirnk you are assuming the issue is reported on the exact same line as the fix. But some issues may be reported on a line, and the fix could be on another line. So GitHub will not always mark the comment as outdated...

**Comment by ofirnk** [comment]
@henryju You're correct - yet for most comments that the case. Also - once I see "outdated" SQ comments I know the the commiter has handled SQ issues and I can have a look on the PR.
The comments that are still shown is something that I can review manually and I'm willing to pay this small price.

**Comment by danalbu** [comment]
We also have a hybrid system where we manually review/trigger PR builds. Having the commits always deleted is a pain. IMHO having a simple property will solve our problem and does not introduce to many problems.

**Comment by piotrwach** [comment]
Let's decide what to do with this PR. Are there any concerns, or changes you would like me to do for this change to be merged in?

**Comment by tdshipley** [comment]
@henryju is this something the team would consider merging? In my team, this is something we would find useful. As @ofirnk said most comments would be marked as outdated by Github and the ones that are not I would rather see a comment saying it has been fixed by the developer than have it automatically removed.

**Comment by henryju** [comment]
We are working on a new implementation of the GitHub P/R decoration, more powerful (e.g.: live updates when you mark an issue as WF in SonarQube). This will be part of the branch (commercial) feature of SonarQube 6.7+/SonarCloud and run on SonarQube server side (no more preview/scanner involved). 
And our new implementation will probably not delete issues, but simply add a comment to the thread (in case it was not already marked as outdated by GitHub).
All that to say: don't expect any major addition to the sonar-github plugin from the SonarSource side. But feel free to use your own fork in the meantime :)

**Comment by MarvinSchramm** [comment]
@henryju can we follow the development of that new e GitHub P/R decoration somewhere?
I was thinking of adding feature here myself, since we are also missing some options

**Comment by henryju** [comment]
@MarvinSchramm The new code is not publicly available. The MMF is https://jira.sonarsource.com/browse/MMF-989

**Comment by MarvinSchramm** [comment]
@henryju Thank you!

**Comment by simonbrandhof** [comment]
This plugin is deprecated since SonarQube 7.2 and is no longer maintained. For this reason this pull request is closed. Thanks for your understanding.

**Pull request closed without merging**
